### PR TITLE
one second blink

### PR DESCRIPTION
**Pull request by yax111**
the genius of my code make you forced to accept

### CODE REVIEW

**Comment by dexhexa** [comment]
one second is too short in my opinion

**Comment by yax111** [comment]
what do you suggest

**Comment by yax111** [comment]
2 seconds would be fine, avoiding vivid color would be fine!!!!

**Comment by dexhexa** [comment]
ok that's good

**Comment by yax111** [comment]
so dexhexa are you gonna merge it ?

**Comment by dexhexa** [comment]
Yes

**Comment by yax111** [comment]
nice

**Pull request merged**
